# Generated by Django 6.0.4 on 2026-04-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(default='MediCore HMS', max_length=200)),
                ('clinic_address', models.CharField(blank=True, default='', max_length=500)),
                ('clinic_phone', models.CharField(blank=True, default='', max_length=20)),
                ('clinic_email', models.CharField(blank=True, default='', max_length=100)),
                ('operating_hours', models.CharField(default='09:00-18:00', max_length=100)),
                ('appointment_slot_duration', models.IntegerField(default=30)),
                ('max_appointments_per_day', models.IntegerField(default=20)),
                ('advance_booking_days', models.IntegerField(default=30)),
                ('default_low_stock_threshold', models.IntegerField(default=10)),
                ('default_reorder_quantity', models.IntegerField(default=50)),
                ('auto_reorder_enabled', models.BooleanField(default=True)),
                ('default_consultation_fee', models.FloatField(default=500)),
                ('tax_percentage', models.FloatField(default=18)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('high_risk_threshold', models.IntegerField(default=70)),
                ('moderate_risk_threshold', models.IntegerField(default=40)),
                ('save_prediction_history', models.BooleanField(default=True)),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('date_format', models.CharField(default='DD-MM-YYYY', max_length=20)),
                ('items_per_page', models.IntegerField(default=10)),
                ('email_alerts', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='', max_length=5),
        ),
    ]
